name: Go

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
        id: go

      - name: Build
        run: |
          CGO_ENABLED=0 GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -trimpath -ldflags="-w -s" -o telegram-wordpress-bot-${{ matrix.goos }}-${{ matrix.goarch }}
          chmod +x telegram-wordpress-bot-${{ matrix.goos }}-${{ matrix.goarch }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: telegram-wordpress-bot-${{ matrix.goos }}-${{ matrix.goarch }}
          path: telegram-wordpress-bot-${{ matrix.goos }}-${{ matrix.goarch }}

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: |
            telegram-wordpress-bot-${{ matrix.goos }}-${{ matrix.goarch }}
